version: '3'
services:
  web:
    build: .
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - .:/app
    command: python app/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - POSTGRES_DB=djinni_sandbox
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=djinni_sandbox
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
